<?php

return [
    'SAFE_BRWOSING_API_URL' => env('SAFE_BRWOSING_API_URL'),
    'SAFE_BRWOSING_API_KEY' => env('SAFE_BRWOSING_API_KEY'),
    'SAFE_BRWOSING_CLIENT_ID' => env('SAFE_BRWOSING_CLIENT_ID'),
    'SAFE_BRWOSING_CLIENT_VERSION' => env('SAFE_BRWOSING_CLIENT_VERSION'),
    'ERROR' => 'error',
    'MESSAGE' => 'message',
    'STATUS_CODE' => 'status_code',
    'SHORT_BASE_URL' => env('SHORT_BASE_URL'),
];